import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import {NextUIProvider} from "@nextui-org/system";
import { UserProvider } from "./userContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
    <html lang="en">
      <body className="flex">
          <Sidebar />
          <div className="flex-1">
            {children}
          </div>
      </body>
    </html>
    </UserProvider>
  );
}
